site: 技术人生
url: http://www.luzexi.com
title: 技术人生
description: '技术，哲学，金融'
twitter:
  username: luzexi
  card: summary
  creator: 陆泽西
author:
  twitter: 陆泽西
  name: 'Jesse Lu'
  avatar:
  email: jesse_luzexi@163.com
  url: http://www.luzexi.com
permalink: pretty

# baseurl: /

# Dependencies
markdown:         redcarpet
highlighter:      pygments

exclude:
  - .jekyll-cache
  
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]

sass:
  sass_dir:          _sass
  style:            :compressed

plugins:
  - jekyll-paginate
  # - jekyll-seo-tag
  - jekyll-sitemap

# plugins
comments:       false
analytics :     true
share: true
advertisement_image: true
advertisement_category: true
advertisement_bottom: true
advertisement_content: true
copyright_info: true
tip_info: true
gongzhonghao: true
relate_article: true
unity3d_book_copyright: true

#donation
paypal_donation: false

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:year/:month/:day/:title
  
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"