# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
# permalink:        pretty
# relative_permalinks: true

# Setup
title:            技术人生
tagline:          'www.luzexi.com'
description:      '漫漫人生,记录点滴技术,始于2013'
url:              http://www.luzexi.com
baseurl:          /

author:
  name:           'Jesse Lu'
  url:            http://www.luzexi.com

gems: [jekyll-paginate]
paginate:         10

excerpt_separator: "\n\n"

# plugins
comments: 		  true
analytics : 	  true
share: true
advertisement_image: true
advertisement_category: true
advertisement_bottom: true
advertisement_content: true

#donation
paypal_donation: true

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/luzexi
