#Analytics
analytics :
    provider : custom

# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            技术人生
tagline:          'luzexi.com'
description:      '漫漫人生,记录点滴,始于2013'
url:              http://www.luzexi.com
baseurl:          /

author:
  name:           'Jesse Lu'
  url:            https://www.luzexi.com

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/luzexi
