# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            技术人生
tagline:          'luzexi.com'
description:      '我将在这里写下我毕生所学---分享是我的一直以来坚持的事,不仅仅是为别人更是为了自己'
url:              http://www.luzexi.com
baseurl:          /

author:
  name:           'Jesse Lu'
  url:            https://www.luzexi.com

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/luzexi
