# frozen_string_literal: true

#source "https://rubygems.org"
source "https://gems.ruby-china.com"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"

gem "jekyll", "~> 3.8.5"
gem 'redcarpet'
gem 'jekyll-paginate'
gem 'pygments.rb'
gem 'json'
gem 'jekyll-sitemap'
gem 'pygments.rb'
